services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_test
      - MYSQL_ROOT_PASSWORD=123